# Generated by Django 3.0.7 on 2020-08-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('categories', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('applicants', models.CharField(max_length=10000)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
