# Generated by Django 3.0.7 on 2020-08-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='applicants',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
